In [2]:
from pathlib import Path
import librosa
import numpy as np
import librosa.display
import IPython.display as ipd

In [3]:
root = Path("./data")

In [4]:
q = root / "query_recordings" / "classical.00000-snippet-10-0.wav"

In [5]:
d = root / "database_recordings" / "classical.00000.wav"

In [6]:
q1, sr1 = librosa.load(q)
d1, sr2 = librosa.load(d)


In [18]:
ipd.Audio(q1, rate=sr1)

In [7]:
ipd.Audio(d1, rate=sr2)

In [ ]:
sr1, sr2

In [8]:
Q = librosa.feature.melspectrogram(y=q1, sr=sr1)

In [9]:
Q.shape

(128, 433)

In [10]:
q1.shape

(221184,)

In [15]:
import torch
x = torch.randn(12, 4)

In [14]:
y = x.T * x

RuntimeError: The size of tensor a (10) must match the size of tensor b (2) at non-singleton dimension 1

In [35]:
for i in range(12):
    for j in range(12):
        a = (x[i].T * x[j]) # 1x4 -> 4x1 * 1x4 -> 4x4
        print(x.shape, x[i].T.shape, x[j].shape, a.shape)
        print(x[i].shape)
        print(a)
        break
    break

torch.Size([12, 4]) torch.Size([4]) torch.Size([4]) torch.Size([4])
torch.Size([4])
tensor([5.3545, 3.1237, 3.4552, 0.2835])


In [41]:
a = torch.mm(x, x.T)

In [42]:
a.shape

torch.Size([12, 12])

In [44]:
x[0], x[1]

(tensor([-2.3140, -1.7674,  1.8588,  0.5324]),
 tensor([-0.3962,  0.0562, -0.2955,  0.8156]))

In [47]:
a[0][1]

tensor(0.7026)

In [48]:
a[1][0]

tensor(0.7026)